joplin_web/urls.py
from django.urls import path, re_path
from joplin_web.views import home, notes_folder, notes_tag, edit_note_and_tags, delete_note, create_folder, create_tag
from joplin_web.api import get_folders, get_tags

urlpatterns = [
    path('', home, name='home'),
    path('create/note/', home, name='create_note'),
    path('create/tag/', create_tag, name='create_tag'),
    path('create/folder/', create_folder, name='create_folder'),
    re_path('^notes/folder/(?P<folder_id>[0-9a-z]{32})', notes_folder, name='notes_folder'),
    re_path('^notes/tag/(?P<tag_id>[0-9a-z]{32})', notes_tag, name='notes_tag'),
    re_path('^notes/(?P<note_id>[0-9a-z]{32})', edit_note_and_tags, name='edit_note_and_tags'),
    re_path('^notes/delete/(?P<note_id>[0-9a-z]{32})', delete_note, name='delete_note'),
    path('folders', get_folders),
    path('tags', get_tags),
]

joplin_web/forms.py
# coding: utf-8
"""
   joplin-web
"""
from django import forms
from django.conf import settings
from joplin_api import JoplinApiSync

joplin = JoplinApiSync(token=settings.JOPLIN_WEBCLIPPER_TOKEN)


def get_children_folders(my_folders, folders):
    for folder in folders:
        my_folders.append((folder['id'], '-> '+folder['title']))

    return my_folders


def get_folders():
    """

    """
    folders = joplin.get_folders().json()

    my_folders = []
    for folder in folders['items']:
        my_folders.append((folder['id'], folder['title']))
        # if 'children' in folder:
        #    my_folders.append(get_children_folders(my_folders, folder['children']))

    return my_folders


def get_tags():
    """

    """
    tags = joplin.get_tags().json()

    my_tags = []
    if 'items' in tags:
        for tag in tags['items']:
            my_tags.append((tag['id'], tag['title']))

    return my_tags


class NoteForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(
        {'class': 'form-control', 'placeholder': 'Title'}))
    tags = forms.MultipleChoiceField(required=False,
                                     widget=forms.SelectMultiple({'class': 'form-control'}),
                                     choices=get_tags())
    parent_id = forms.ChoiceField(label="Folder",
                                  widget=forms.Select({'class': 'form-control'}),
                                  choices=get_folders())
    text = forms.CharField(widget=forms.Textarea({'class': 'form-control', 'rows': 20}))


class FolderForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput({'class': 'form-control', 'placeholder': 'Title'}))


class TagForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput({'class': 'form-control', 'placeholder': 'Title'}))

joplin_web/views.py
# coding: utf-8
"""
   joplin-web
"""
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from joplin_api import JoplinApiSync
from joplin_web.forms import NoteForm, FolderForm, TagForm
from joplin_web.utils import tag_for_notes
import logging

from rich import console
console = console.Console()

logger = logging.getLogger("joplin_web.app")

joplin = JoplinApiSync(token=settings.JOPLIN_WEBCLIPPER_TOKEN)


def home(request, *args, **kwargs):
    template_name = "index.html"
    form_folder = FolderForm()
    form_tag = TagForm()
    res = joplin.get_notes()
    notes = tag_for_notes(res)

    form = NoteForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            title = form.cleaned_data['title']
            text = form.cleaned_data['text']
            parent_id = form.cleaned_data['parent_id']
            tags = form.cleaned_data['tags']
            data = dict()
            data['tags'] = tags
            res = joplin.create_note(title=title, body=text, parent_id=parent_id, **data)
            form = NoteForm()
    else:
        form = NoteForm()
    console.print(len(notes))
    context = {"notes": notes, "form": form, 'form_tag': form_tag, 'form_folder': form_folder}

    return render(request, template_name, context)


def edit_note_and_tags(request, note_id, *args, **kwargs):
    """
    edit one note and provide its tags too
    :param request
    :param note_id the note to modify
    :return HttpResponse
    """
    template_name = "index.html"
    # to keep only the data of the folder if provided
    folder_id = request.GET.get('folder_id', '')
    tag_id = request.GET.get('tag_id', '')
    if folder_id:
        notes = joplin.get_folders_notes(folder_id)
        # res = joplin.get_folders_notes(folder_id)
        # notes = tag_for_notes(res)
    elif tag_id:
        notes = joplin.get_tags_notes(tag_id)
    else:
        notes = joplin.get_notes()

    note = joplin.get_note(note_id)

    data = note.json()
    tags = joplin.get_notes_tags(data['id'])

    if request.POST:
        form = NoteForm(request.POST, initial={'parent_id': data['parent_id']})
        if form.is_valid():
            title = form.cleaned_data['title']
            text = form.cleaned_data['text']
            parent_id = form.cleaned_data['parent_id']
            data = dict()
            data['tags'] = form.cleaned_data['tags']
            res = joplin.update_note(note_id=note_id, title=title, body=text, parent_id=parent_id, **data)
            if res.status_code == 200:
                messages.add_message(request, messages.INFO, "Note updated successfully")
    else:
        form = NoteForm()
        tags_list = []
        for tag in tags.json()['items']:
            tags_list.append(tag['id'])
        form.initial['tags'] = tags_list
        form.initial['parent_id'] = data['parent_id']
        form.initial['title'] = data['title']
        form.initial['text'] = data['body']

    context = {"notes": notes.json()['items'],
               "note": note,
               "note_id": note_id,
               "folder_id": folder_id,
               "tag_id": tag_id,
               "form": form}

    return render(request, template_name, context)


def notes_folder(request, folder_id, *args, **kwargs):
    """
    get all the notes of that folder
    :param request
    :param folder_id: id of the folder we want to filter
    :return HttpResponse
    """
    template_name = "index.html"
    res = joplin.get_folders_notes(folder_id)
    notes = res.json()['items'] if 'items' in res.json() else []
    form = NoteForm()
    context = {"notes": notes, "form": form, 'folder_id': folder_id}
    return render(request, template_name, context)


def notes_tag(request, tag_id, *args, **kwargs):
    """
    get all the notes of that tag
    :param request
    :param tag_id: id of the tag we want to filter
    :return HttpResponse
    """
    template_name = "index.html"
    res = joplin.get_tags_notes(tag_id)
    notes = res.json()['items'] if 'items' in res.json() else []
    form = NoteForm()
    context = {"notes": notes, "form": form, 'tag_id': tag_id}

    return render(request, template_name, context)


def create_folder(request):
    form = FolderForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            title = form.cleaned_data['title']
            joplin.create_folder(title)
    return HttpResponseRedirect(reverse('home'))


def create_tag(request):
    form = TagForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            title = form.cleaned_data['title']
            joplin.create_tag(title)
    return HttpResponseRedirect(reverse('home'))


def delete_note(request, note_id, *args, **kwargs):
    """
    delete a note
    :param request
    :param note_id: id of the folder we want to delete
    :return HttpResponse
    """
    joplin.delete_note(note_id)
    return HttpResponseRedirect(reverse('home'))


def delete_tag(request, tag_id, *args, **kwargs):
    """
    delete a tag
    :param request
    :param tag_id: id of the tag we want to delete
    :return HttpResponse
    """
    joplin.delete_tag(tag_id)
    return HttpResponseRedirect(reverse('home'))


def delete_folder(request, folder_id, *args, **kwargs):
    """
    delete a folder
    :param request
    :param folder_id: id of the folder we want to delete
    :return HttpResponse
    """
    joplin.delete_folder(folder_id)
    return HttpResponseRedirect(reverse('home'))

joplin_web/templates/folders_child_list.html
            <ul class="list-group d-flew justify-content-between align-items-center">
              {% for folder in parent_folder %}
              <li class="list-group-item">
                  <a href="/notes/folder/{{ folder.id }}">{{ folder.title }}</a>
                  <span class="badge badge-pill badge-primary">{{ folder.nb_notes }}</span>
                  {% if folder.children %}
                  {% include 'folders_child_list.html' with parent_folder=folder.children %}
                  {% endif %}
              </li>
              {% endfor %}
            </ul>

joplin_web/templates/folders_list.html
    <div class="accordion" id="accordionJoplinFolder">
      <div class="card">
        <div class="card-header" id="headingJoplinFolder">
          <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseJoplinFolder" aria-expanded="true" aria-controls="collapseJoplinFolder">
              <i class="fas fa-folder-open"></i> Folders
            </button>
          </h2>
        </div>
        <div id="collapseJoplinFolder" class="collapse show" aria-labelledby="headingJoplinFolder" data-parent="#accordionJoplinFolder">
          <div id="folders_tree"></div>
        </div>
      </div>
    </div>
{% block extra_js %}
<script type="text/javascript">
//<![CDATA[
$(document).ready(function() {
  $.ajax({url: '/folders',
            type: 'get',
            dataType: 'json',
    }).done(function(data) {
        $('#folders_tree').bstreeview({
          data: data,
          expandIcon: 'fa fa-angle-down fa-fw',
          collapseIcon: 'fa fa-angle-right fa-fw',
          indent: 1.25,
          parentsMarginLeft: '1.25rem',
          openNodeLinkOnNewTab: false
        });
    })
  });
//]]>
</script>
{% endblock %}

joplin_web/templates/index.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="fr" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">-
    <link rel="stylesheet" href="{% static 'bstreeview/css/bstreeview.min.css' %}" media="screen">
    <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
    <title>Joplin Web</title>
    <meta name="author" content="FoxMaSk">{% block myhead %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top sticky-top">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'home' %}">
      <i class="fas fa-seedling"></i>
      <span class="menu-collapsed">Joplin Web</span>
  </a>
  <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
    <li class="nav-item">
      <a type="button" class="btn btn-primary" href="{% url 'create_note' %}"><i class="fas fa-plus-circle"></i> {% trans 'Create note' %}</a>
    </li>
    <li class="nav-item">
        <a type="button" class="btn btn-primary" data-toggle="modal" data-target="#tagCreateModal"><i class="fas fa-plus-circle"></i> {% trans 'Create tag' %}</a>
    </li>
    <li class="nav-item">
      <a type="button" class="btn btn-primary" data-toggle="modal" data-target="#folderCreateModal"><i class="fas fa-plus-circle"></i> {% trans 'Create folder' %}</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    {% block content %}
    <div class="col-2">
      {% include 'folders_list.html' with folders=folders %}
      {% include 'tags_list.html' with tags=tags %}
    </div>
    <div class="col-2">
      {% include 'notes_list.html' with notes=notes %}
    </div>
    <div class="col-8">
      {% include 'take_note.html' %}
    </div>
    {% endblock %}
  </div>
</div>
<hr/>
<footer class="footer">
    <div class="container">
        <p>2018 - {% now "Y" %} <a href="https://gitlab.com/annyong/joplin-web">Joplin Web</a></p>
    </div>
</footer>

<!-- Modal to create Folder and Tag -->
<div class="modal fade" id="folderCreateModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="folderCreateModalLabel">{% trans 'New Folder' %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{% url 'create_folder' %}" method="post">{% csrf_token %}
      <div class="modal-body">
        {{ form_folder.non_field_errors }}
        <div class="form-group">
            {{ form_folder.title.errors }}
            {{ form_folder.title }}
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">{% trans "Close" %}</button>
        <input type="submit" class="btn btn-outline-primary" value="{% trans 'Create' %}">
      </div>
      </form>
    </div>
  </div>
</div>

<div class="modal fade" id="tagCreateModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="tagCreateModalLabel">{% trans 'New Tag' %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{% url 'create_tag' %}" method="post">{% csrf_token %}
      <div class="modal-body">
        {{ form_tag.non_field_errors }}
        <div class="form-group">
            {{ form_tag.title.errors }}
            {{ form_tag.title }}
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">{% trans "Close" %}</button>
        <input type="submit" class="btn btn-outline-primary" value="{% trans 'Create' %}">
      </div>
      </form>
    </div>
  </div>
</div>
<!-- End Modal to create Folder and Tag -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="{% static 'bstreeview/js/bstreeview.min.js' %}"></script>
{% block extra_js %}
{% endblock %}
</body>
</html>

joplin_web/templates/notes_list.html
{% for note in notes %}
  <div class="card">
    <div class="card-body">
        {% if folder_id %}
        <h5 class="card-title"><a href="/notes/{{ note.id }}?folder_id={{ note.parent_id }}">{{ note.title }}</a></h5>
        {% elif tag_id %}
        <h5 class="card-title"><a href="/notes/{{ note.id }}?tag_id={{ tag_id }}">{{ note.title }}</a></h5>
        {% else %}
        <h5 class="card-title"><a href="/notes/{{ note.id }}">{{ note.title }}</a></h5>
        {% for tag in note.tag %}
        <p class="card-text">
            <small class="text-muted"><a href="/notes/tag/{{ tag.id }}" class="btn btn-outline-success" role="button">{{ tag.title }}</a></small>
        </p>
        {% endfor %}
        {% endif %}
    </div>
  </div>
{% endfor %}

joplin_web/templates/tags_list.html
    <div class="accordion" id="accordionJoplinTag">
      <div class="card">
        <div class="card-header" id="headingJoplinTag">
          <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseJoplinTag" aria-expanded="true" aria-controls="collapseJoplinTag">
              <i class="fas fa-tags"></i> Tags
            </button>
          </h2>
        </div>
        <div id="collapseJoplinTag" class="collapse show" aria-labelledby="headingJoplinTag" data-parent="#accordionJoplinTag">
          <div id="tags_tree"></div>
        </div>
      </div>
    </div>
{% block extra_js %}
<script type="text/javascript">
//<![CDATA[
$(document).ready(function() {
    $.ajax({url: '/tags',
            type: 'get',
            dataType: 'json',
    }).done(function(data) {
        $('#tags_tree').bstreeview({
          data: data,
          expandIcon: 'fa fa-angle-down fa-fw',
          collapseIcon: 'fa fa-angle-right fa-fw',
          indent: 1.25,
          parentsMarginLeft: '1.25rem',
          openNodeLinkOnNewTab: false
        });
    })
  });
//]]>
</script>
{% endblock %}

joplin_web/templates/take_note.html
{% load i18n %}
<div class="col-12">
    <div class="row">
    <div class="col-6">
        <form method="post" class="form-vertical"
              action="{% if note_id %}{% url 'edit_note_and_tags' note_id %}{% else %}{% url 'create_note' %}{% endif %}">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form-group">
                <label for="id_title">{% trans 'Title' %}</label>
                {{ form.title.errors }}
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="id_parent_id">{% trans 'Folders' %}</label>
                {{ form.parent_id.errors }}
                {{ form.parent_id }}
            </div>
            <div class="form-group">
                <label for="id_tags">{% trans 'Tags' %}</label>
                {{ form.tags.errors }}
                {{ form.tags }}
            </div>
            <div class="form-group">
                {{ form.text.errors }}
                {{ form.text }}
            </div>
            {% if note_id %}
            <input type="submit" class="btn btn-outline-primary" value="{% trans 'Submit' %}">
            <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal">{% trans 'Delete' %}</button>
            <div class="modal fade" id="deleteModal">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">{% trans 'Deletion' %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <p>{% trans 'Do you confirm the deletion of that note ?' %} {{ note_title }}</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">{% trans 'No' %}</button>
                    <a href="{% url 'delete_note' note_id %}" type="submit" class="btn btn-outline-danger">{% trans 'Yes' %}</a>
                  </div>
                </div>
              </div>
            </div>
            {% else %}
            <input type="submit" class="btn btn-outline-primary" value="{% trans 'Submit' %}">
            {% endif %}
        </form>
    </div>
    <div class="col-6">
        <h5>Preview</h5>
    </div>
    </div>
</div>